#ifndef STATUSCODES_H
#define STATUSCODES_H

#define ERROR_VALUE_OUT_OF_RANGE 1
#define ERROR_INVALID_NUMBER 2
#define ERROR_INVALID_BINARY_STRING_CHARACTER 3
#define ERROR_INVALID_BINARY_STRING_LENGTH 4
#define ERROR_UNKNOWN_REGISTER 5
#define ERROR_UNKNOWN_MNEMONIC 6
#define ERROR_DUPLICATE_LABEL 7
#define ERROR_MISSING_INSTRUCTION_PARAMETER 8
#define ERROR_INVALID_ARGUMENTS 9
#define ERROR_SYMBOLS_LIST_NULL 10
#define ERROR_INSTRUCTION_FOLLOWS_LABEL 11
#define ERROR_NO_SPACE_AFTER_LABEL 12
#define ERROR_TOO_MANY_TOKENS 13

#define STATUS_LINE_CONTAINED_INSTRUCTION 254
#define STATUS_LINE_NOT_INSTRUCTION 255

#endif
